"""alembic_init

Revision ID: 221ed68e2a6d
Revises: 
Create Date: 2021-04-26 18:42:53.929215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221ed68e2a6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
